# Generated by Django 4.0.4 on 2022-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_now_app', '0003_remove_product_is_headline_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatars'),
        ),
    ]
