# Generated by Django 4.0.4 on 2022-08-08 15:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_now_app', '0004_alter_publisher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog_now_app.publisher'),
        ),
    ]
