# Generated by Django 4.0.4 on 2022-08-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_now_app', '0009_alter_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_published',
        ),
    ]
