# Generated by Django 4.0.4 on 2022-08-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_now_app', '0010_remove_product_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='whatsapp_phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
