# Generated by Django 4.0.4 on 2022-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_now_app', '0011_catalog_whatsapp_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='social_network_two',
            new_name='social_network_instagram',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='social_network_three',
            new_name='social_network_linkedin',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='social_network_one',
            new_name='social_network_twitter',
        ),
    ]
